[package]
name = "langmangler"
version = "0.2.0"
authors = ["Piotr Grabowski <fau999@gmail.com>"]
edition = "2018"

[dependencies]
itertools = "0.10.4"
clap = "3.2.22"
quit = "1.1"
regex = "1.6.0"
once-cell-regex = "0.2.1"
deunicode = "1.3.2"
