[package]
name = "langmangler"
version = "0.2.0"
authors = ["Piotr Grabowski <fau999@gmail.com>"]
edition = "2018"

[dependencies]
itertools = "0.10.0"
clap = "2.33.3"
quit = "1.1"
regex = "1"
once_cell = "0.1.2"
deunicode = "1.2.0"
